pairs = [
    ("How do I change my email?", "You can update it in your profile settings."),
    ("How can I reset my password?", "Use the password reset link on the login page."),
    ("My order is delayed", "Your order may take a little longer than expected."),
    ("Where can I track my package?", "You can track your package in the orders section."),
    ("How do I cancel my subscription?", "Open billing settings and click cancel subscription."),
    ("I forgot my username", "Please contact support to recover your username."),
    ("Can I change delivery address?", "Yes, you can update the address before shipping."),
    ("Payment failed", "Please try another payment method or contact your bank."),
    ("How long is shipping?", "Shipping usually takes three to five business days."),
    ("App is crashing", "Please reinstall the app and try again."),
    ("How do I contact support?", "You can contact support via live chat."),
    ("Can I get a refund?", "Refund requests are available within thirty days."),
    ("My promo code does not work", "Please check if the promo code is still valid."),
    ("How do I delete my account?", "Go to account settings and choose delete account."),
    ("I cannot log in", "Please verify your email and password."),
    ("Is international shipping available?", "Yes, we ship to most countries."),
    ("How do I update payment method?", "Open billing settings to update your payment method."),
    ("Order not received", "Please wait a little longer or contact support."),
    ("Can I return an item?", "Yes, returns are accepted within fourteen days."),
    ("Website is slow", "We are currently working on performance improvements."),
    ("How do I enable notifications?", "You can enable notifications in app settings."),
    ("Can I change my password?", "Go to security settings to change your password."),
    ("Why was my account suspended?", "Please contact support for account review."),
    ("How do I download invoice?", "Invoices are available in billing history."),
    ("Do you offer discounts?", "Special discounts are available during promotions.")
]